# Generated by Django 3.1.6 on 2021-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('percent', models.PositiveSmallIntegerField(verbose_name='Percent')),
                ('iteration_number', models.FloatField(primary_key=True, serialize=False, verbose_name='Iteration number')),
                ('scheme', models.TextField(verbose_name='Scheme')),
                ('disk_in_motion', models.PositiveIntegerField(blank=True, verbose_name='Disk in motion')),
            ],
        ),
    ]
