# Generated by Django 3.1.6 on 2021-05-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanoiTowersApp', '0002_auto_20210507_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='disk_in_motion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Disk in motion'),
        ),
    ]
