# Generated by Django 3.1.6 on 2021-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='Commands')),
                ('output', models.TextField(verbose_name='Outputs')),
            ],
        ),
    ]
