# Generated by Django 3.1.6 on 2021-02-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_commandbuffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandBuffer',
        ),
    ]
